server {
    listen 80;

    # supplierA
    location = /supplierA { return 301 /supplierA/; }
    location /supplierA/ {
        client_max_body_size 50m;
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://supplierA-env:8081/;
    }

    # supplierB
    location = /supplierB { return 301 /supplierB/; }
    location /supplierB/ {
        client_max_body_size 50m;
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://supplierB-env:8081/;
    }

    # supplierC
    location = /supplierC { return 301 /supplierC/; }
    location /supplierC/ {
        client_max_body_size 50m;
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://supplierC-env:8081/;
    }

    # supplierD
    location = /supplierD { return 301 /supplierD/; }
    location /supplierD/ {
        client_max_body_size 50m;
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://supplierD-env:8081/;
    }

    # supplierE
    location = /supplierE { return 301 /supplierE/; }
    location /supplierE/ {
        client_max_body_size 50m;
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://supplierE-env:8081/;
    }

    # semantic dictionary
    location = /semantic { return 301 /semantic/; }
    location /semantic/ {
        client_max_body_size 50m;
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://semantic-env:8081/;
    }
}
