server.port=8081
basyx.backend=InMemory

# Registry integration
basyx.aasrepository.feature.registryintegration=http://aas-registry:8080
basyx.submodelrepository.feature.registryintegration=http://submodel-registry:8080

basyx.externalurl=http://localhost:8080/supplierC

basyx.cors.allowed-origins=*
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
